-- Here you are going to add all your blacklisted models, if you DON'T know what are you doing, leave it default and follow the tutorial
-- If you already know what im talking about, add everything to make your server safer
-- Don't forget commas!!

ChocoHaxANBM = {}

ChocoHaxANBM.BlacklistedWeapons = {
	"WEAPON_DAGGER",
	"WEAPON_PROXMINE",
	"WEAPON_PROXMINE",
	"WEAPON_RAYMINIGUN",
	"WEAPON_COMPACTLAUNCHER",
	"WEAPON_HOMINGLAUNCHER",
	"WEAPON_RAILGUN",
	"WEAPON_FIREWORK",
	"WEAPON_MINIGUN",
	"WEAPON_GRENADELAUNCHER_SMOKE",
	"WEAPON_GRENADELAUNCHER",
	"WEAPON_RPG",
	"WEAPON_MARKSMANRIFLE_MK2",
	"WEAPON_MARKSMANRIFLE",
	"WEAPON_HEAVYSNIPER_MK2",
	-- "WEAPON_HEAVYSNIPER",
	"WEAPON_SNIPERRIFLE",
	-- "WEAPON_GUSENBERG",
	"WEAPON_COMBATMG_MK2",
	"WEAPON_COMBATMG",
	"WEAPON_MG",
	"WEAPON_COMPACTRIFLE",
	"WEAPON_BULLPUPRIFLE_MK2",
	"WEAPON_BULLPUPRIFLE", 
	"WEAPON_SPECIALCARBINE_MK2", 
	-- "WEAPON_SPECIALCARBINE",
	-- "WEAPON_ADVANCEDRIFLE",
	"WEAPON_CARBINERIFLE_MK2",
	"WEAPON_ASSAULTRIFLE_MK2",
	"WEAPON_AUTOSHOTGUN",
	"WEAPON_DBSHOTGUN",
	"WEAPON_HEAVYSHOTGUN",
	"WEAPON_MUSKET",
	"WEAPON_BULLPUPSHOTGUN",
	"WEAPON_ASSAULTSHOTGUN",
	"WEAPON_SAWNOFFSHOTGUN", 
	"WEAPON_PUMPSHOTGUN_MK2",
	-- "WEAPON_PUMPSHOTGUN",
	"WEAPON_RAYCARBINE",
	"WEAPON_MINISMG",
	"WEAPON_MACHINEPISTOL",
	-- "WEAPON_COMBATPDW",
	"WEAPON_SMG_MK2",
	-- "WEAPON_MICROSMG",
	"WEAPON_NAVYREVOLVER",
	"WEAPON_CERAMICPISTOL",
	"WEAPON_RAYPISTOL",
	"WEAPON_DOUBLEACTION",
	"WEAPON_REVOLVER_MK2",
	"WEAPON_REVOLVER",
    "WEAPON_MARKSMANPISTOL",
    "WEAPON_PISTOL_MK2",
    "WEAPON_SNSPISTOL_MK2",
	"WEAPON_FLAREGUN",
	"WEAPON_VINTAGEPISTOL",
	"WEAPON_APPISTOL",
	"WEAPON_BOTTLE",
	"WEAPON_GOLFCLUB",
	"WEAPON_POOLCUE",
	"WEAPON_SMOKEGRENADE",
	"WEAPON_SNOWBALL",
    "WEAPON_FLARE"
}

ChocoHaxANBM.BlacklistedVehicles = { -- Vehicles
	"cargoplane",
}

ChocoHaxANBM.BlacklistedObjects = { -- Entities
	"prop_fnclink_05crnr1",
	"xs_prop_hamburgher_wl",
	"xs_prop_plastic_bottle_wl",
	"prop_windmill_01",
	"p_spinning_anus_s",
	"stt_prop_ramp_adj_flip_m",
	"stt_prop_ramp_adj_flip_mb",
	"stt_prop_ramp_adj_flip_s",
	"stt_prop_ramp_adj_flip_sb",
	"stt_prop_ramp_adj_hloop",
	"stt_prop_ramp_adj_loop",
	"stt_prop_ramp_jump_l",
	"stt_prop_ramp_jump_m",
	"stt_prop_ramp_jump_s",
	"stt_prop_ramp_jump_xl",
	"stt_prop_ramp_jump_xs",
	"stt_prop_ramp_jump_xxl",
	"stt_prop_ramp_multi_loop_rb",
	"stt_prop_ramp_spiral_l",
	"stt_prop_ramp_spiral_l_l",
	"stt_prop_ramp_spiral_l_m",
	"stt_prop_ramp_spiral_l_s",
	"stt_prop_ramp_spiral_l_xxl",
	"stt_prop_ramp_spiral_m",
	"stt_prop_ramp_spiral_s",
	"stt_prop_ramp_spiral_xxl",
}

ChocoHaxANBM.BlacklistedPeds = { -- Peds, animals, etc.
	"s_m_y_swat_01",
	"a_m_y_mexthug_01", 
    "a_c_cat_01", 
    "a_c_boar", 
    "a_c_sharkhammer", 
    "a_c_coyote", 
    "a_c_chimp",  
    "a_c_cow", 
    "a_c_deer", 
    "a_c_dolphin", 
    "a_c_fish", 
    "a_c_hen", 
    "a_c_humpback", 
    "a_c_killerwhale", 
    "a_c_mtlion",
    "a_c_rabbit_01",  
    "a_c_rhesus",  
    "a_c_sharktiger", 
	"u_m_y_zombie_01"
}

