RegisterNetEvent('esx_highend:applyUpgrades')
AddEventHandler('esx_highend:applyUpgrades', function(netId, props)
    local vehicle = NetworkGetEntityFromNetworkId(netId)
    SetNetworkIdCanMigrate(netId, true)
    SetEntityAsMissionEntity(vehicle, true, false)
    SetVehicleHasBeenOwnedByPlayer(vehicle, true)
    SetVehicleNeedsToBeHotwired(vehicle, false)
    SetVehicleAutoRepairDisabled(vehicle, true)
end)